# Generated by Django 3.2.8 on 2021-12-18 16:19

import Users.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='actions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('done', 'done'), ('dismissed', 'dismissed')], default='scheduled', max_length=30)),
                ('action', models.ForeignKey(db_column='action', on_delete=django.db.models.deletion.CASCADE, to='Appointments.actions')),
                ('add_by', models.ForeignKey(db_column='add_by', on_delete=models.SET(Users.models.get_deleted_employee), to='Users.employees')),
                ('customer', models.ForeignKey(db_column='customer', on_delete=django.db.models.deletion.CASCADE, to='Users.customers')),
                ('employee', models.ForeignKey(blank=True, db_column='employee', null=True, on_delete=models.SET(Users.models.get_deleted_employee), related_name='appointment_employee', to='Users.employees')),
            ],
        ),
    ]
