# Generated by Django 3.2.8 on 2021-11-02 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_emails'),
        ('Appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='client',
        ),
        migrations.AddField(
            model_name='appointments',
            name='customer',
            field=models.ForeignKey(db_column='customer', default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.customers'),
            preserve_default=False,
        ),
    ]
