# Generated by Django 3.2.8 on 2021-12-19 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='action',
            field=models.ForeignKey(blank=True, db_column='action', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appointments.actions'),
        ),
    ]
