# Generated by Django 3.2.8 on 2021-12-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0002_alter_appointments_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='duration',
            field=models.CharField(max_length=10),
        ),
    ]
