# Generated by Django 3.2.8 on 2021-12-17 12:51

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0021_rolepermissions_can_show_employees'),
        ('Appointments', '0003_alter_appointments_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='add_by',
            field=models.ForeignKey(db_column='add_by', on_delete=models.SET(Users.models.get_deleted_employee), to='Users.employees'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='employee',
            field=models.ForeignKey(blank=True, db_column='employee', null=True, on_delete=models.SET(Users.models.get_deleted_employee), related_name='appointment_employee', to='Users.employees'),
        ),
    ]
