# Generated by Django 3.2.8 on 2021-10-25 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Store', '0002_auto_20211025_1007'),
        ('Users', '0007_auto_20211025_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_terms', models.SmallIntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('discount_type', models.CharField(blank=True, choices=[('percentage(%)', 'percentage'), ('Amount', 'Amount')], max_length=20, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('shipping_fees', models.SmallIntegerField(blank=True, null=True)),
                ('shipping_details', models.CharField(choices=[('auto', 'auto'), ("don't show", "don't show")], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'cash'), ('cheque', 'cheque'), ('bank transfer', 'bank transfer'), ('paytabs', 'paytabs')], default='cash', max_length=20)),
                ('payment_no', models.IntegerField(blank=True, null=True)),
                ('total', models.FloatField()),
                ('Client', models.ForeignKey(db_column='Client', on_delete=django.db.models.deletion.CASCADE, to='Users.customers')),
                ('sold_by', models.ForeignKey(db_column='add_by', on_delete=django.db.models.deletion.CASCADE, to='Users.employees')),
                ('warehouse', models.ForeignKey(db_column='warehouse', on_delete=django.db.models.deletion.CASCADE, to='Store.warehouses')),
            ],
        ),
        migrations.CreateModel(
            name='SalePayments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('cash', 'cash'), ('cheque', 'cheque'), ('bank transfer', 'bank transfer'), ('paytabs', 'paytabs')], max_length=20)),
                ('ref_no', models.SmallIntegerField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('payment_details', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='PurchasePayments_attachments/%y/%m')),
                ('Amount', models.IntegerField()),
                ('status', models.CharField(choices=[('incomplete', 'incomplete'), ('complete', 'complete'), ('pending', 'pending'), ('failed', 'failed')], default='completed', max_length=20)),
                ('Collected_by', models.ForeignKey(db_column='Collected_by', on_delete=django.db.models.deletion.CASCADE, to='Users.employees')),
            ],
        ),
        migrations.CreateModel(
            name='SaleInvoice_products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.SmallIntegerField()),
                ('unit_price', models.SmallIntegerField()),
                ('count_after', models.SmallIntegerField()),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, to='Store.products')),
                ('purchase_invoice', models.ForeignKey(db_column='purchase_invoice', on_delete=django.db.models.deletion.CASCADE, to='Sales.saleinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attachments', models.FileField(upload_to='PurchaseInvoice_attachments/%y/%m')),
                ('sale_invoice', models.ForeignKey(db_column='purchase_invoice', on_delete=django.db.models.deletion.CASCADE, to='Sales.saleinvoice')),
            ],
        ),
    ]
