# Generated by Django 3.2.8 on 2021-12-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'percentage'), ('Amount', 'Amount')], max_length=20, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('shipping_fees', models.SmallIntegerField(blank=True, null=True)),
                ('shipping_details', models.CharField(choices=[('auto', 'auto'), ("don't show", "don't show")], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment_terms', models.SmallIntegerField(blank=True, null=True)),
                ('total', models.FloatField()),
                ('date', models.DateField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='sales/%y/%m')),
            ],
        ),
        migrations.CreateModel(
            name='SaleInvoice_products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.SmallIntegerField()),
                ('unit_price', models.SmallIntegerField()),
                ('count_after', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SalePayments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('cash', 'cash'), ('cheque', 'cheque'), ('bank transfer', 'bank transfer'), ('paytabs', 'paytabs')], max_length=20)),
                ('ref_no', models.CharField(blank=True, max_length=25, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('payment_details', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='sales/%y/%m')),
                ('Amount', models.IntegerField()),
                ('status', models.CharField(choices=[('incomplete', 'incomplete'), ('complete', 'complete'), ('pending', 'pending'), ('failed', 'failed')], default='completed', max_length=20)),
                ('manual', models.BooleanField(default=False)),
            ],
        ),
    ]
