# Generated by Django 3.2.8 on 2021-10-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='attachments',
            field=models.FileField(upload_to='SalesInvoice_attachments/%y/%m'),
        ),
        migrations.AlterField(
            model_name='salepayments',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='SalePayments_attachments/%y/%m'),
        ),
    ]
