# Generated by Django 3.2.8 on 2021-12-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='shipping_details',
            field=models.CharField(blank=True, choices=[('auto', 'auto'), ("don't show", "don't show")], max_length=20, null=True),
        ),
    ]
