# Generated by Django 3.2.8 on 2021-10-25 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_auto_20211025_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachments',
            old_name='attachments',
            new_name='attachment',
        ),
    ]
