# Generated by Django 3.2.8 on 2021-11-02 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_emails'),
        ('Sales', '0004_rename_attachments_attachments_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleinvoice',
            name='Client',
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='customer',
            field=models.ForeignKey(db_column='customer', default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.customers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachments',
            name='attachment',
            field=models.FileField(upload_to='Files/%y/%m'),
        ),
        migrations.AlterField(
            model_name='salepayments',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='Files/%y/%m'),
        ),
    ]
