# Generated by Django 3.2.8 on 2021-11-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0008_alter_saleinvoice_products_sales_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='attachment',
            field=models.FileField(upload_to='sales/%y/%m'),
        ),
        migrations.AlterField(
            model_name='salepayments',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='sales/%y/%m'),
        ),
    ]
