# Generated by Django 3.2.8 on 2021-11-14 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_auto_20211102_1043'),
        ('Sales', '0009_auto_20211114_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='sale_invoice',
            field=models.ForeignKey(db_column='purchase_invoice', on_delete=django.db.models.deletion.CASCADE, related_name='Attachments', to='Sales.saleinvoice'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='sold_by',
            field=models.ForeignKey(db_column='sold_by', on_delete=django.db.models.deletion.CASCADE, to='Users.employees'),
        ),
    ]
