# Generated by Django 3.2.8 on 2021-11-18 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0010_auto_20211114_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepayments',
            name='sales_invoice',
            field=models.ForeignKey(db_column='sales_invoice', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='SalePayments', to='Sales.saleinvoice'),
            preserve_default=False,
        ),
    ]
