# Generated by Django 3.2.8 on 2021-11-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0014_salepayments_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepayments',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
