# Generated by Django 3.2.8 on 2021-11-25 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_auto_20211124_2315'),
        ('Sales', '0016_auto_20211122_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice_products',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, related_name='SaleInvoice', to='Store.products'),
        ),
    ]
