# Generated by Django 3.2.8 on 2021-12-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0017_alter_saleinvoice_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
