# Generated by Django 3.2.8 on 2021-12-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0018_saleinvoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleinvoice',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='payment_no',
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'percentage'), ('Amount', 'Amount')], max_length=20, null=True),
        ),
    ]
