# Generated by Django 3.2.8 on 2021-12-17 12:51

import Users.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_products_barcode'),
        ('Users', '0021_rolepermissions_can_show_employees'),
        ('Sales', '0019_auto_20211215_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='sold_by',
            field=models.ForeignKey(db_column='sold_by', on_delete=models.SET(Users.models.get_deleted_employee), related_name='SaleInvoice_employee', to='Users.employees'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='warehouse',
            field=models.ForeignKey(db_column='warehouse', on_delete=django.db.models.deletion.PROTECT, to='Store.warehouses'),
        ),
        migrations.AlterField(
            model_name='saleinvoice_products',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.PROTECT, related_name='SaleInvoice', to='Store.products'),
        ),
        migrations.AlterField(
            model_name='saleinvoice_products',
            name='tax1',
            field=models.ForeignKey(blank=True, db_column='tax1', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saleseInvoice_tax', to='Users.tax'),
        ),
        migrations.AlterField(
            model_name='saleinvoice_products',
            name='tax2',
            field=models.ForeignKey(blank=True, db_column='tax2', null=True, on_delete=django.db.models.deletion.PROTECT, to='Users.tax'),
        ),
        migrations.AlterField(
            model_name='salepayments',
            name='Collected_by',
            field=models.ForeignKey(db_column='Collected_by', on_delete=models.SET(Users.models.get_deleted_employee), related_name='SalePayments_user', to='Users.employees'),
        ),
    ]
