# Generated by Django 3.2.8 on 2021-12-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0020_auto_20211217_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepayments',
            name='ref_no',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
