# Generated by Django 3.2.8 on 2021-12-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0021_alter_salepayments_ref_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='sales/%y/%m'),
        ),
        migrations.AlterField(
            model_name='salepayments',
            name='ref_no',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='Attachments',
        ),
    ]
