# Generated by Django 3.2.8 on 2021-12-18 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0023_auto_20211218_1524'),
        ('Sales', '0022_auto_20211218_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='sales_officer',
            field=models.ForeignKey(blank=True, db_column='sales_officer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_officer', to='Users.employees'),
        ),
    ]
