# Generated by Django 3.2.8 on 2021-10-23 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0005_auto_20211023_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPermissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField()),
                ('add_by', models.ForeignKey(db_column='supplier', on_delete=django.db.models.deletion.CASCADE, to='Users.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OutPermissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField()),
                ('add_by', models.ForeignKey(db_column='supplier', on_delete=django.db.models.deletion.CASCADE, to='Users.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('selling_price', models.SmallIntegerField()),
                ('purchasing_price', models.SmallIntegerField()),
                ('mini_selling_price', models.SmallIntegerField()),
                ('count', models.IntegerField()),
                ('mini_count', models.SmallIntegerField()),
                ('notes', models.TextField()),
                ('deactivate', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(db_column='supplier', on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='Users.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, to='Store.categories')),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, to='Store.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsBrand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Brand', models.ForeignKey(db_column='Brand', on_delete=django.db.models.deletion.CASCADE, to='Store.brands')),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, to='Store.products')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='warehouse',
            field=models.ForeignKey(db_column='warehouse', on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='Store.warehouses'),
        ),
        migrations.CreateModel(
            name='OutPermissions_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('count_after', models.SmallIntegerField()),
                ('out_permission', models.ForeignKey(db_column='out_permission', on_delete=django.db.models.deletion.CASCADE, to='Store.outpermissions')),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, to='Store.products')),
            ],
        ),
        migrations.AddField(
            model_name='outpermissions',
            name='warehouse',
            field=models.ForeignKey(db_column='warehouse', on_delete=django.db.models.deletion.CASCADE, to='Store.warehouses'),
        ),
        migrations.CreateModel(
            name='AddPermissions_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('count_after', models.SmallIntegerField()),
                ('add_permission', models.ForeignKey(db_column='add_permission', on_delete=django.db.models.deletion.CASCADE, to='Store.addpermissions')),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, to='Store.products')),
            ],
        ),
        migrations.AddField(
            model_name='addpermissions',
            name='warehouse',
            field=models.ForeignKey(db_column='warehouse', on_delete=django.db.models.deletion.CASCADE, to='Store.warehouses'),
        ),
    ]
