# Generated by Django 3.2.8 on 2021-10-25 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20211025_1007'),
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpermissions',
            name='add_by',
            field=models.ForeignKey(db_column='add_by', on_delete=django.db.models.deletion.CASCADE, to='Users.employees'),
        ),
        migrations.AlterField(
            model_name='outpermissions',
            name='add_by',
            field=models.ForeignKey(db_column='add_by', on_delete=django.db.models.deletion.CASCADE, to='Users.employees'),
        ),
        migrations.AlterField(
            model_name='productsbrand',
            name='Brand',
            field=models.ForeignKey(db_column='brand', on_delete=django.db.models.deletion.CASCADE, to='Store.brands'),
        ),
    ]
