# Generated by Django 3.2.8 on 2021-12-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpermissions',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outpermissions',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
