# Generated by Django 3.2.8 on 2021-10-26 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20211025_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='count',
        ),
        migrations.CreateModel(
            name='Product_count',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.SmallIntegerField()),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, to='Store.products')),
                ('warehouse', models.ForeignKey(db_column='warehouse', on_delete=django.db.models.deletion.CASCADE, to='Store.warehouses')),
            ],
        ),
    ]
