# Generated by Django 3.2.8 on 2021-12-20 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_auto_20211219_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscategory',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='Store.products'),
        ),
    ]
