# Generated by Django 3.2.8 on 2021-11-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_auto_20211026_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='warehouse',
        ),
    ]
