# Generated by Django 3.2.8 on 2021-11-24 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_remove_products_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_count',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, related_name='Product_count', to='Store.products'),
        ),
        migrations.AlterField(
            model_name='productsbrand',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, related_name='Brand', to='Store.products'),
        ),
        migrations.AlterField(
            model_name='productscategory',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='Store.products'),
        ),
    ]
