# Generated by Django 3.2.8 on 2021-12-20 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_suppliers_add_by'),
        ('Store', '0004_alter_productscategory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='supplier',
            field=models.ForeignKey(blank=True, db_column='supplier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier', to='Users.suppliers'),
        ),
    ]
