# Generated by Django 3.2.8 on 2021-11-24 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_auto_20211124_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsbrand',
            name='Brand',
            field=models.ForeignKey(db_column='brand', on_delete=django.db.models.deletion.CASCADE, related_name='Brand', to='Store.brands'),
        ),
        migrations.AlterField(
            model_name='productscategory',
            name='category',
            field=models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='Store.categories'),
        ),
    ]
