# Generated by Django 3.2.8 on 2021-12-20 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_products_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpermissions',
            name='warehouse',
            field=models.ForeignKey(db_column='warehouse', on_delete=django.db.models.deletion.PROTECT, to='Store.warehouses'),
        ),
        migrations.AlterField(
            model_name='outpermissions',
            name='warehouse',
            field=models.ForeignKey(db_column='warehouse', on_delete=django.db.models.deletion.PROTECT, to='Store.warehouses'),
        ),
        migrations.AlterField(
            model_name='product_count',
            name='warehouse',
            field=models.ForeignKey(db_column='warehouse', on_delete=django.db.models.deletion.PROTECT, to='Store.warehouses'),
        ),
    ]
