# Generated by Django 3.2.8 on 2021-11-24 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_auto_20211124_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(blank=True, db_column='brand', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Brand', to='Store.brands'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='mini_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='mini_selling_price',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='purchasing_price',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='selling_price',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProductsBrand',
        ),
    ]
