# Generated by Django 3.2.8 on 2021-11-26 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_auto_20211124_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpermissions_products',
            name='add_permission',
            field=models.ForeignKey(db_column='add_permission', on_delete=django.db.models.deletion.CASCADE, related_name='AddPermissions_Products', to='Store.addpermissions'),
        ),
        migrations.AlterField(
            model_name='addpermissions_products',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, related_name='AddPermissions_Products', to='Store.products'),
        ),
        migrations.AlterField(
            model_name='outpermissions_products',
            name='out_permission',
            field=models.ForeignKey(db_column='out_permission', on_delete=django.db.models.deletion.CASCADE, related_name='OutPermissions_Products', to='Store.outpermissions'),
        ),
        migrations.AlterField(
            model_name='outpermissions_products',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, related_name='OutPermissions_Products', to='Store.products'),
        ),
    ]
