# Generated by Django 3.2.8 on 2021-11-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_auto_20211126_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpermissions_products',
            name='unit_price',
            field=models.SmallIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outpermissions_products',
            name='unit_price',
            field=models.SmallIntegerField(default=12),
            preserve_default=False,
        ),
    ]
