# Generated by Django 3.2.8 on 2021-12-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_auto_20211126_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouses',
            name='deactivate',
            field=models.BooleanField(default=False),
        ),
    ]
