# Generated by Django 3.2.8 on 2021-12-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_warehouses_deactivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='barcode',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
