# Generated by Django 3.2.8 on 2021-12-17 12:51

import Users.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0021_rolepermissions_can_show_employees'),
        ('Store', '0011_products_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpermissions',
            name='add_by',
            field=models.ForeignKey(db_column='add_by', on_delete=models.SET(Users.models.get_deleted_employee), to='Users.employees'),
        ),
        migrations.AlterField(
            model_name='addpermissions_products',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.PROTECT, related_name='AddPermissions_Products', to='Store.products'),
        ),
        migrations.AlterField(
            model_name='outpermissions',
            name='add_by',
            field=models.ForeignKey(db_column='add_by', on_delete=models.SET(Users.models.get_deleted_employee), to='Users.employees'),
        ),
        migrations.AlterField(
            model_name='outpermissions_products',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.PROTECT, related_name='OutPermissions_Products', to='Store.products'),
        ),
        migrations.AlterField(
            model_name='productscategory',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.PROTECT, related_name='Category', to='Store.products'),
        ),
    ]
