# Generated by Django 3.2.8 on 2021-12-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepayments',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
