# Generated by Django 3.2.8 on 2021-10-25 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_tax'),
        ('Purchases', '0002_auto_20211025_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice_products',
            name='tax1',
            field=models.ForeignKey(blank=True, db_column='tax1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseInvoice_tax', to='Users.tax'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice_products',
            name='tax2',
            field=models.ForeignKey(blank=True, db_column='tax2', null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.tax'),
        ),
    ]
