# Generated by Django 3.2.8 on 2021-12-04 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0005_auto_20211102_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='attachment',
            field=models.FileField(upload_to='Purchases/%y/%m'),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='purchase_invoice',
            field=models.ForeignKey(db_column='purchase_invoice', on_delete=django.db.models.deletion.CASCADE, related_name='Attachments', to='Purchases.purchaseinvoice'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice_products',
            name='purchase_invoice',
            field=models.ForeignKey(db_column='purchase_invoice', on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseInvoice_products', to='Purchases.purchaseinvoice'),
        ),
        migrations.AlterField(
            model_name='purchasepayments',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='Purchases/%y/%m'),
        ),
    ]
