# Generated by Django 3.2.8 on 2021-12-04 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0006_auto_20211204_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepayments',
            name='purchase_invoice',
            field=models.ForeignKey(db_column='purchase_invoice', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PurchasePayments', to='Purchases.purchaseinvoice'),
            preserve_default=False,
        ),
    ]
