# Generated by Django 3.2.8 on 2021-12-15 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0008_purchaseinvoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='payment_no',
        ),
    ]
