# Generated by Django 3.2.8 on 2021-12-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0010_auto_20211217_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='Purchases/%y/%m'),
        ),
        migrations.AlterField(
            model_name='purchasepayments',
            name='ref_no',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='Attachments',
        ),
    ]
