# Generated by Django 3.2.8 on 2021-12-19 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='role',
            field=models.ForeignKey(db_column='role', on_delete=django.db.models.deletion.PROTECT, to='Users.rolepermissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
