# Generated by Django 3.2.8 on 2021-10-23 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=10)),
                ('can_add_product', models.BooleanField(default=False)),
                ('can_show_products', models.BooleanField(default=False)),
                ('can_edit_Or_delete_products', models.BooleanField(default=False)),
                ('can_add_saleBill', models.BooleanField(default=False)),
                ('can_show_saleBills', models.BooleanField(default=False)),
                ('can_show_his_saleBills', models.BooleanField(default=False)),
                ('can_edit_Or_delete_saleBill', models.BooleanField(default=False)),
                ('can_add_paymentForBills', models.BooleanField(default=False)),
                ('can_edit_feesSettings', models.BooleanField(default=False)),
                ('can_add_customer', models.BooleanField(default=False)),
                ('can_show_customers', models.BooleanField(default=False)),
                ('can_edit_Or_delete_customers', models.BooleanField(default=False)),
                ('can_add_storePermission', models.BooleanField(default=False)),
                ('can_edit_Or_delete_storePermission', models.BooleanField(default=False)),
                ('can_show_storePermissions', models.BooleanField(default=False)),
                ('can_add_purchaseBill', models.BooleanField(default=False)),
                ('can_edit_Or_delete_purchaseBill', models.BooleanField(default=False)),
                ('can_show_purchaseBills', models.BooleanField(default=False)),
                ('can_show_his_purchaseBills', models.BooleanField(default=False)),
                ('can_add_supplier', models.BooleanField(default=False)),
                ('can_edit_Or_delete_supplier', models.BooleanField(default=False)),
                ('can_show_suppliers', models.BooleanField(default=False)),
                ('can_show_his_suppliers', models.BooleanField(default=False)),
                ('can_add_notes', models.BooleanField(default=False)),
                ('can_add_employee', models.BooleanField(default=False)),
                ('can_edit_Or_delete_employee', models.BooleanField(default=False)),
                ('can_management_roles', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='type',
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('photo', models.ImageField(upload_to='employee/%y/%m/%d')),
                ('role', models.ForeignKey(db_column='role', on_delete=django.db.models.deletion.CASCADE, to='Users.rolepermissions')),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=10)),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
