# Generated by Django 3.2.8 on 2021-10-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20211023_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
