# Generated by Django 3.2.8 on 2021-12-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20211219_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermissions',
            name='create_appointment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermissions',
            name='delete_appointment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermissions',
            name='show_appointment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermissions',
            name='update_appointment',
            field=models.BooleanField(default=False),
        ),
    ]
