# Generated by Django 3.2.8 on 2021-10-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20211023_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trade_name', models.CharField(max_length=25)),
                ('Tax_card', models.BigIntegerField()),
                ('commercial_record', models.SmallIntegerField()),
                ('currency', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('customer', 'customer'), ('employee', 'employee'), ('supplier', 'supplier')], default='customer', max_length=8),
        ),
    ]
