# Generated by Django 3.2.8 on 2021-12-20 10:58

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20211220_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='add_by',
            field=models.ForeignKey(blank=True, db_column='employee', null=True, on_delete=models.SET(Users.models.get_deleted_employee), to='Users.employees'),
        ),
    ]
