# Generated by Django 3.2.8 on 2021-12-20 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_auto_20211220_1357'),
        ('Users', '0005_suppliers_add_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordhistory',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product', null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.products'),
        ),
    ]
