# Generated by Django 3.2.8 on 2021-10-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20211023_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliers',
            old_name='trade_name',
            new_name='business_name',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='Tax_card',
        ),
        migrations.AddField(
            model_name='suppliers',
            name='Tax_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee/%y/%m'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='commercial_record',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
