# Generated by Django 3.2.8 on 2021-10-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20211025_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tax_name', models.CharField(max_length=30)),
                ('tax_value', models.PositiveSmallIntegerField()),
                ('product_included', models.CharField(choices=[('inclusive', 'inclusive'), ('exclusive', 'exclusive')], max_length=10)),
            ],
        ),
    ]
