# Generated by Django 3.2.8 on 2021-10-25 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_rename_attachments_attachments_attachment'),
        ('Users', '0009_auto_20211025_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='emails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=30)),
                ('send_form', models.CharField(max_length=50)),
                ('send_to', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('attachment', models.FileField(upload_to='email_attachments/%y/%m')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(db_column='invoice', on_delete=django.db.models.deletion.CASCADE, to='Sales.saleinvoice')),
            ],
        ),
    ]
