# Generated by Django 3.2.8 on 2021-11-02 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0005_auto_20211102_1043'),
        ('Store', '0004_remove_products_warehouse'),
        ('Sales', '0005_auto_20211102_1043'),
        ('Users', '0010_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='deletedActivities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment', models.PositiveSmallIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('cash', 'cash'), ('cheque', 'cheque'), ('bank transfer', 'bank transfer'), ('paytabs', 'paytabs')], max_length=15)),
                ('status', models.CharField(choices=[('incomplete', 'incomplete'), ('complete', 'complete'), ('pending', 'pending'), ('failed', 'failed')], max_length=20)),
                ('item_count', models.PositiveSmallIntegerField()),
                ('store_count', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField()),
                ('type', models.CharField(choices=[('customer', 'customer'), ('employee', 'employee')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='emails',
            name='attachment',
            field=models.FileField(upload_to='Files/%y/%m'),
        ),
        migrations.CreateModel(
            name='RecordHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('update_Store', 'update_Store'), ('update_invoice', 'update_invoice'), ('delete_product', 'update_invoice'), ('sold_product', 'sold_product'), ('create_payment', 'create_payment'), ('update_payment', 'update_payment'), ('delete_payment', 'delete_payment'), ('add_addPermission', 'add_addPermission'), ('add_outPermission', 'add_outPermission'), ('delete_addPermission', 'delete_addPermission'), ('delete_outPermission', 'delete_outPermission'), ('receive_product', 'receive_product'), ('create_purchase', 'create_purchase'), ('create_sale', 'create_sale'), ('send_email', 'send_email'), ('create_appointment', 'create_appointment'), ('update_appointment', 'update_appointment'), ('delete_appointment', 'delete_appointment'), ('move_product', 'move_product')], max_length=20)),
                ('activity_id', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('add_by', models.ForeignKey(blank=True, db_column='add_by', null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.employees')),
                ('customer', models.ForeignKey(blank=True, db_column='customer', null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.customers')),
                ('employee', models.ForeignKey(blank=True, db_column='employee', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='Users.employees')),
                ('product', models.ForeignKey(blank=True, db_column='product', null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.products')),
                ('purchase', models.ForeignKey(blank=True, db_column='purchase', null=True, on_delete=django.db.models.deletion.CASCADE, to='Purchases.purchaseinvoice')),
                ('sale', models.ForeignKey(blank=True, db_column='sale', null=True, on_delete=django.db.models.deletion.CASCADE, to='Sales.saleinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='NotesAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attachment', models.FileField(upload_to='Files/%y/%m')),
                ('note', models.ForeignKey(db_column='note', on_delete=django.db.models.deletion.CASCADE, to='Users.notes')),
            ],
        ),
    ]
