# Generated by Django 3.2.8 on 2021-11-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_auto_20211102_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedactivities',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deletedactivities',
            name='item_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deletedactivities',
            name='payment',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deletedactivities',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'cash'), ('cheque', 'cheque'), ('bank transfer', 'bank transfer'), ('paytabs', 'paytabs')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='deletedactivities',
            name='status',
            field=models.CharField(blank=True, choices=[('incomplete', 'incomplete'), ('complete', 'complete'), ('pending', 'pending'), ('failed', 'failed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deletedactivities',
            name='store_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recordhistory',
            name='type',
            field=models.CharField(choices=[('update_Store', 'update_Store'), ('update_invoice', 'update_invoice'), ('sold_product', 'sold_product'), ('create_payment', 'create_payment'), ('update_payment', 'update_payment'), ('delete_payment', 'delete_payment'), ('add_addPermission', 'add_addPermission'), ('add_outPermission', 'add_outPermission'), ('delete_addPermission', 'delete_addPermission'), ('delete_outPermission', 'delete_outPermission'), ('receive_product', 'receive_product'), ('create_purchase', 'create_purchase'), ('create_sale', 'create_sale'), ('send_email', 'send_email'), ('create_appointment', 'create_appointment'), ('update_appointment', 'update_appointment'), ('delete_appointment', 'delete_appointment'), ('move_product', 'move_product'), ('update_product_invoice', 'update_product_invoice'), ('delete_product_invoice', 'delete_product_invoice'), ('update_product', 'update_product')], max_length=25),
        ),
    ]
