# Generated by Django 3.2.8 on 2021-11-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_auto_20211120_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedactivities',
            name='product',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
