# Generated by Django 3.2.8 on 2021-11-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_auto_20211126_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordhistory',
            name='type',
            field=models.CharField(choices=[('update_Store', 'update_Store'), ('update_invoice', 'update_invoice'), ('sold_product', 'sold_product'), ('create_payment', 'create_payment'), ('update_payment', 'update_payment'), ('delete_payment', 'delete_payment'), ('add_addPermission', 'add_addPermission'), ('add_outPermission', 'add_outPermission'), ('update_outPermission', 'update_outPermission'), ('update_addPermission', 'update_addPermission'), ('delete_addPermission', 'delete_addPermission'), ('delete_outPermission', 'delete_outPermission'), ('product_addPermission', 'product_addPermission'), ('product_outPermission', 'product_outPermission'), ('delete_product_outPermission', 'product_outPermission'), ('receive_product', 'receive_product'), ('create_purchase', 'create_purchase'), ('create_sale', 'create_sale'), ('send_email', 'send_email'), ('create_appointment', 'create_appointment'), ('update_appointment', 'update_appointment'), ('delete_appointment', 'delete_appointment'), ('move_product', 'move_product'), ('update_product_invoice', 'update_product_invoice'), ('delete_product_invoice', 'delete_product_invoice'), ('update_product', 'update_product')], max_length=40),
        ),
    ]
