# Generated by Django 3.2.8 on 2021-12-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_remove_suppliers_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='person_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notesattachment',
            name='attachment',
            field=models.FileField(upload_to='Notes/%y/%m'),
        ),
    ]
