# Generated by Django 3.2.8 on 2021-12-13 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0019_auto_20211210_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='active',
        ),
        migrations.RemoveField(
            model_name='rolepermissions',
            name='can_show_his_suppliers',
        ),
    ]
