# Generated by Django 3.2.8 on 2021-12-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0020_auto_20211213_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermissions',
            name='can_show_employees',
            field=models.BooleanField(default=False),
        ),
    ]
