# Generated by Django 3.2.8 on 2021-12-17 12:51

import Users.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_auto_20211217_1451'),
        ('Users', '0021_rolepermissions_can_show_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordhistory',
            name='employee',
            field=models.ForeignKey(blank=True, db_column='employee', null=True, on_delete=models.SET(Users.models.get_deleted_employee), related_name='employee', to='Users.employees'),
        ),
        migrations.AlterField(
            model_name='recordhistory',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product', null=True, on_delete=django.db.models.deletion.PROTECT, to='Store.products'),
        ),
        migrations.AlterField(
            model_name='recordhistory',
            name='type',
            field=models.CharField(choices=[('update_Store', 'update_Store'), ('update_invoice', 'update_invoice'), ('sold_product', 'sold_product'), ('create_payment', 'create_payment'), ('update_payment', 'update_payment'), ('delete_payment', 'delete_payment'), ('add_addPermission', 'add_addPermission'), ('add_outPermission', 'add_outPermission'), ('update_outPermission', 'update_outPermission'), ('update_addPermission', 'update_addPermission'), ('delete_addPermission', 'delete_addPermission'), ('delete_outPermission', 'delete_outPermission'), ('update_product_addPermission', 'update_product_addPermission'), ('update_product_outPermission', 'update_product_outPermission'), ('add_product_addPermission', 'add_product_addPermission'), ('add_product_outPermission', 'add_product_outPermission'), ('delete_product_outPermission', 'delete_product_outPermission'), ('delete_product_addPermission', 'delete_product_addPermission'), ('receive_product', 'receive_product'), ('create_purchase', 'create_purchase'), ('create_sale', 'create_sale'), ('send_email', 'send_email'), ('create_appointment', 'create_appointment'), ('update_appointment', 'update_appointment'), ('delete_appointment', 'delete_appointment'), ('show_appointment', 'show_appointment'), ('move_product', 'move_product'), ('update_product_invoice', 'update_product_invoice'), ('delete_product_invoice', 'delete_product_invoice'), ('update_product', 'update_product')], max_length=40),
        ),
    ]
