# Generated by Django 3.2.8 on 2021-12-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0022_auto_20211217_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='Notes/%y/%m'),
        ),
        migrations.DeleteModel(
            name='NotesAttachment',
        ),
    ]
